export const SET_LOADING = 'SET_LOADING';
export const FETCH_TRENDING_NOW = 'FETCH_TRENDING_NOW';
export const FETCH_BY_QUERY = 'FETCH_BY_QUERY';
export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT';
