export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const INVALID_SIGNIN = 'INVALID_SIGNIN';
export const INVALID_SIGNUP = 'INVALID_SIGNUP';
